// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace FCG.TestsReqnroll.Features.Application.Users.UseCases
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AtualizacaoDePromocaoDeJogosADMINFeature : object, global::Xunit.IClassFixture<AtualizacaoDePromocaoDeJogosADMINFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt-br"), "Features/Application/Users/UseCases", "Atualização de Promoção de Jogos ADMIN", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "AdminCreateUserUseCaseTests.feature"
#line hidden
        
        public AtualizacaoDePromocaoDeJogosADMINFeature(AtualizacaoDePromocaoDeJogosADMINFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 4
  #line hidden
#line 5
    await testRunner.GivenAsync("que o ID do cargo de administrador é definido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 6
    await testRunner.AndAsync("que o ID do cargo de usuário comum é definido", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Application/Users/UseCases/AdminCreateUserUseCaseTests.feature.ndjson", 7);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Tentativa de atualização por usuário sem permissão")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Atualização de Promoção de Jogos ADMIN")]
        [global::Xunit.TraitAttribute("Description", "Tentativa de atualização por usuário sem permissão")]
        public async global::System.Threading.Tasks.Task TentativaDeAtualizacaoPorUsuarioSemPermissao()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tentativa de atualização por usuário sem permissão", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 8
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 9
    await testRunner.GivenAsync("que existe uma promoção cadastrada no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 10
    await testRunner.WhenAsync("um usuário comum tentar atualizar essa promoção", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 11
    await testRunner.ThenAsync("deve ser lançada uma exceção de permissão insuficiente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 12
    await testRunner.AndAsync("as alterações não devem ser persistidas no banco", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Tentativa de atualização de promoção inexistente")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Atualização de Promoção de Jogos ADMIN")]
        [global::Xunit.TraitAttribute("Description", "Tentativa de atualização de promoção inexistente")]
        public async global::System.Threading.Tasks.Task TentativaDeAtualizacaoDePromocaoInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tentativa de atualização de promoção inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 15
    await testRunner.GivenAsync("que uma promoção com ID específico não existe no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 16
    await testRunner.WhenAsync("um administrador tentar atualizar uma promoção inexistente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 17
    await testRunner.ThenAsync("deve ser lançada uma exceção de promoção não encontrada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Tentativa de atualização com sobreposição de datas")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Atualização de Promoção de Jogos ADMIN")]
        [global::Xunit.TraitAttribute("Description", "Tentativa de atualização com sobreposição de datas")]
        public async global::System.Threading.Tasks.Task TentativaDeAtualizacaoComSobreposicaoDeDatas()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tentativa de atualização com sobreposição de datas", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 20
    await testRunner.GivenAsync("que existe uma promoção cadastrada no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 21
    await testRunner.AndAsync("existe uma outra promoção ativa que sobrepõe o novo período", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 22
    await testRunner.WhenAsync("um administrador tentar atualizar essa promoção alterando as datas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 23
    await testRunner.ThenAsync("deve ser lançada uma exceção de sobreposição de promoção", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 24
    await testRunner.AndAsync("as alterações não devem ser persistidas no banco", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Atualização de promoção com sucesso")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Atualização de Promoção de Jogos ADMIN")]
        [global::Xunit.TraitAttribute("Description", "Atualização de promoção com sucesso")]
        public async global::System.Threading.Tasks.Task AtualizacaoDePromocaoComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Atualização de promoção com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 26
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 27
    await testRunner.GivenAsync("que existe uma promoção cadastrada no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 28
    await testRunner.AndAsync("não existem promoções sobrepostas para o novo período", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 29
    await testRunner.WhenAsync("um administrador tentar atualizar essa promoção para um valor fixo de 5.99", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 30
    await testRunner.ThenAsync("a promoção deve ser atualizada com sucesso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 31
    await testRunner.AndAsync("os detalhes da promoção devem refletir o novo valor de 5.99", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 32
    await testRunner.AndAsync("as alterações devem ser persistidas no banco uma única vez", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Desativação de promoção sem validar sobreposição")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Atualização de Promoção de Jogos ADMIN")]
        [global::Xunit.TraitAttribute("Description", "Desativação de promoção sem validar sobreposição")]
        public async global::System.Threading.Tasks.Task DesativacaoDePromocaoSemValidarSobreposicao()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Desativação de promoção sem validar sobreposição", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await this.FeatureBackgroundAsync();
#line hidden
#line 35
    await testRunner.GivenAsync("que existe uma promoção cadastrada no sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 36
    await testRunner.WhenAsync("um administrador solicitar a desativação da promoção", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 37
    await testRunner.ThenAsync("a promoção deve ser desativada com sucesso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 38
    await testRunner.AndAsync("o sistema não deve validar a sobreposição de promoções", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 39
    await testRunner.AndAsync("as alterações devem ser persistidas no banco uma única vez", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await AtualizacaoDePromocaoDeJogosADMINFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await AtualizacaoDePromocaoDeJogosADMINFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
